name: EventsMod
version: 1.12
author: bms_
main: io.bms.events.EventsMod
commands:
   runevent:
      description: This command runs an event, either randomly chosen or specified.
      usage: /runevent [event name]
      permission: eventsmod.event.runevent
      permission-message: You don't have permission to run that command.